#!/usr/bin/env python3
"""Rootless, checksum-locked binary toolchain bootstrap; never rewrites pins.

The committed lock was derived from signature-verified repository metadata.
TLS and SHA-256 remain required on every download. No package maintainer
scripts run; only the C/LLVM development subset is extracted into .deps.
"""
import hashlib
import json
import os
from pathlib import Path
import platform
import shlex
import shutil
import subprocess
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "scripts/toolchain-lock.json"


def sha256(path: Path) -> str:
    result = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            result.update(chunk)
    return result.hexdigest()


def run(args: list[str], environment: dict[str, str] | None = None) -> str:
    return subprocess.check_output(args, env=environment, text=True,
                                   stderr=subprocess.STDOUT).strip()


def main() -> None:
    if platform.system() != "Linux" or platform.machine() != "x86_64":
        raise SystemExit("P0 bootstrap supports Linux x86_64 only")
    if shutil.which("dpkg-deb") is None or shutil.which("gcc") is None:
        raise SystemExit("Install dpkg and the host C toolchain first; see README")
    release = platform.freedesktop_os_release()
    target = f"{release['ID']}-{release['VERSION_ID']}-x86_64"
    lock = json.loads(LOCK.read_text())
    llvm_major = lock["llvm_version"].split(".")[0]
    if target not in lock["platforms"]:
        raise SystemExit(f"No reviewed toolchain lock for {target}")
    if target == "ubuntu-24.04-x86_64":
        # The tag-matching Trixie SDK uses the locked Z3 4.13.3 runtime on
        # Ubuntu too. Its GLIBCXX_3.4.32 requirement needs the distro's GCC 14
        # runtime, independently of using GCC 13 as the C host compiler.
        runtime = run(["dpkg-query", "-W", "-f=${Version}", "libstdc++6"])
        if subprocess.run(["dpkg", "--compare-versions", runtime, "ge", "14"]).returncode:
            raise SystemExit("Ubuntu requires libstdc++6 >=14; install README prerequisites")
    identity = hashlib.sha256(LOCK.read_bytes()).hexdigest()[:16]
    prefix = ROOT / ".deps/toolchains" / f"{target}-{identity}"
    cache = ROOT / ".deps/downloads"
    prefix.mkdir(parents=True, exist_ok=True)
    cache.mkdir(parents=True, exist_ok=True)
    completed = prefix / ".complete"
    # Dedicated content-addressed prefix; partial extraction is retried from
    # the same verified artifacts. Dependencies retained in the snapshot.
    for package in lock["platforms"][target]["packages"]:
        path = cache / f"{package['name']}-{package['sha256']}.deb"
        if not path.is_file() or sha256(path) != package["sha256"]:
            temporary = path.with_suffix(".partial")
            print(f"download {package['name']} {package['version']}", flush=True)
            with urllib.request.urlopen(package["url"], timeout=60) as response:
                with temporary.open("wb") as output:
                    shutil.copyfileobj(response, output)
            if sha256(temporary) != package["sha256"]:
                temporary.unlink()
                raise SystemExit(f"checksum mismatch: {package['name']}")
            temporary.replace(path)
        if not completed.is_file():
            subprocess.run(["dpkg-deb", "-x", str(path), str(prefix)], check=True)

    environment = os.environ.copy()
    bindir = str(prefix / "usr/bin")
    libdir = str(prefix / "usr/lib/x86_64-linux-gnu")
    environment["PATH"] = bindir + os.pathsep + environment["PATH"]
    environment["LD_LIBRARY_PATH"] = libdir + (
        os.pathsep + environment["LD_LIBRARY_PATH"]
        if environment.get("LD_LIBRARY_PATH") else "")
    llvm_config = prefix / f"usr/bin/llvm-config-{llvm_major}"
    llvm = run([str(llvm_config), "--version"], environment)
    if llvm != lock["llvm_version"]:
        raise SystemExit(f"LLVM version mismatch: {llvm}")
    clang = run([str(prefix / f"usr/bin/clang-{llvm_major}"), "--version"], environment)
    cmake = run(["cmake", "--version"], environment)
    gcc = run(["gcc", "-dumpfullversion"], environment)
    print(f"LLVM {llvm}\n{clang.splitlines()[0]}\n"
          f"GCC {gcc}\n{cmake.splitlines()[0]}\nPython {platform.python_version()}")

    # Activation is required for shared libraries and compiler executables.
    activate = ROOT / ".deps/activate.sh"
    marker = "# Generated by NewLang P0 bootstrap; no credentials.\n"
    if activate.exists() and not activate.read_text().startswith(marker):
        raise SystemExit("Preserving unfamiliar .deps/activate.sh; move it before bootstrap")
    activate.write_text(marker +
        f"export PATH={shlex.quote(bindir)}:\"$PATH\"\n" +
        f"export LD_LIBRARY_PATH={shlex.quote(libdir)}"
        '"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"\n' +
        f"export LLVM_CONFIG={shlex.quote(str(llvm_config))}\n")
    completed.write_text(identity + "\n")
    print("Bootstrap verified. Run: . .deps/activate.sh")


if __name__ == "__main__":
    main()
